# Generated by Django 4.1.3 on 2023-08-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OptiKartPortal", "0002_rename_newsletter_newsmail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "ProdID",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("Name", models.CharField(max_length=50)),
                ("Desc", models.TextField(max_length=5000)),
                ("Seller", models.CharField(max_length=50)),
                ("Rating", models.IntegerField()),
                ("Price", models.IntegerField()),
                ("Image", models.CharField(max_length=200)),
            ],
        ),
    ]
