# Generated by Django 4.1.3 on 2023-08-05 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("OptiKartPortal", "0003_products"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Products",
            new_name="Product",
        ),
    ]
