# Generated by Django 4.1.3 on 2023-08-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OptiKartPortal", "0004_rename_products_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=200)),
                ("Desc", models.CharField(max_length=200)),
                ("Post", models.TextField(max_length=5000)),
                ("Date", models.DateField()),
                ("Views", models.IntegerField()),
            ],
        ),
    ]
