# Generated by Django 4.1.3 on 2023-08-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OptiKartPortal", "0005_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="Image",
            field=models.CharField(default="", max_length=50),
        ),
    ]
