# Generated by Django 4.1.3 on 2023-08-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OptiKartPortal", "0009_product_actrates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="ActRates",
            field=models.CharField(default="0", max_length=20),
        ),
        migrations.AlterField(
            model_name="product",
            name="Rates",
            field=models.CharField(default="0", max_length=20),
        ),
        migrations.AlterField(
            model_name="product",
            name="Rating",
            field=models.IntegerField(default=0),
        ),
    ]
