# Generated by Django 4.1.3 on 2023-08-20 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("OptiKartPortal", "0012_orderstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderstatus",
            name="User",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="OrderUserDetails",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
