# Generated by Django 4.1.3 on 2023-08-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("OptiKartPortal", "0016_rename_product_orderstatus_orderproduct_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderstatus",
            old_name="OrderProduct",
            new_name="Product",
        ),
        migrations.RenameField(
            model_name="orderstatus",
            old_name="OrderUser",
            new_name="User",
        ),
    ]
