# Generated by Django 4.1.3 on 2023-08-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OptiKartPortal", "0017_rename_orderproduct_orderstatus_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eyenumber",
            name="Left",
            field=models.CharField(default="0", max_length=10),
        ),
        migrations.AlterField(
            model_name="eyenumber",
            name="Right",
            field=models.CharField(default="0", max_length=10),
        ),
    ]
